server:
    port: 8080

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /me/**
      url: http://localhost:9999/uaa/me

security:
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
    resource:
       jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn
           Gp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6u
           R3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5Xa
           A0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqy
           nT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQy
           zKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sf
           ZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscu
           WG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22C
           IMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
           -----END PUBLIC KEY-----

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG