server:
  port: 9000
        
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn
          Gp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6u
          R3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5Xa
          A0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqy
          nT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQy
          zKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sf
          ZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscu
          WG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22C
          IMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----